### ISSUE TITLE
Periodic builds

### ISSUE THREAD

**Issue by ryanprior** [naqvis/wasmer-crystal#1]
Hi there, thank you for publishing this shard! Can you set up periodic builds against the latest Crystal, so we can catch early if there are any hiccups?

**Comment by Blacksmoke16** [comment]
There already is: https://github.com/naqvis/wasmer-crystal/blob/main/.github/workflows/ci.yml#L7-L8.

**Comment by ryanprior** [comment]
Sweet, I missed that. Thank you @Blacksmoke16!
